- hosts: targets
  become: true
  # pre_tasks:
  #   - name: update repositories
  #     apt: update_cache=yes
  #     changed_when: False
  vars_files:
  - "vars/main.yml"

  tasks:
    - include: tasks/talk.yml
