---
- name: hello 
  debug:
    msg: "Hello"
  tags:
    - hello
- name: bye 
  debug:
    msg: "Bye"
- name: Execute the command in remote shell
  shell: cat /etc/os-release
  register: os_release

- debug: var=os_release.stdout_lines

- name: Run a script with arguments (free form)
  script: "{{ playbook_dir }}/files/script1.sh"
  register: script1
  changed_when: script1.stdout != 'EXISTS'
  #https://stackoverflow.com/questions/23945201/how-to-run-only-one-task-in-ansible-playbook
  tags:
    - deploy

- debug: var=script1.stdout_lines

- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Upgrade all apt packages
  apt: upgrade=dist force_apt_get=yes

  #https://ansibledaily.com/idempotent-shell-command-in-ansible/
- name: shell script with idempotentcy
  shell: >
         cat /tmp/bob
         && echo -n EXISTS
         || touch /tmp/bob
  register: file_exists
  changed_when: file_exists.stdout != 'EXISTS'